project:
  type: website
  output-dir: docs
  
website:
  title: "Zoe PhD Info"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: C1-Partitioning Algorithms.qmd
        text: C1-Partitioning Algorithms  
      - href: C2-Seasonal Vars of CUE.qmd
        text: C2-Seasonal Vars of CUE
      - href: C3-Coordination of MCUE VCUE.qmd
        text: C3-Coordination of MCUE VCUE
      - href: EC_basic.qmd
        text: EC Basic
    tools:
      - icon: github
        href: https://github.com/ZoeZHH
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Hehan (Zoe) Zhang"

format:
  html:
    theme: cosmo
    toc: true

editor: source
