project:
  type: website
  output-dir: docs
  
website:
  title: "Zoe PhD Info"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - C1-Partitioning Algorithms.qmd
      - C2-Seasonal Vars of CUE.qmd
      - C3-Coordination of MCUE/VCUE.qmd
    tools:
      - icon: github
        href: https://github.com/ZoeZHH
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Hehan (Zoe) Zhang"

format:
  html:
    theme: cerulean
    toc: true

editor: source

