---
title: ""
format:
  html:
    toc: true
    title-block-style: none
---

# CHAPTER 1-Improving Daytime Partitioning Algorithms in Eddy Covariance Observations: Incorporating Absorbed PAR and Canopy Temperature

**Overview:** An eddy covariance (EC) flux tower equipped with gas analyzers continuously measures the exchange of carbon flux between land and atmosphere. With over 1,400 EC towers operating globally, this network plays a key role in monitoring the terrestrial carbon cycle. The CO~2~ analyzer provides measurements of net ecosystem exchange (NEE), which represents the balance between carbon uptake through photosynthesis (gross primary production, GPP) and carbon release through ecosystem respiration (R~eco~). However, GPP and R~eco~ are not directly measured and must be estimated by applying partitioning algorithms to the NEE data. Current partitioning methods have limitations in accuracy. In this study, we aim to improve these algorithms by incorporating more precise measurements of absorbed photosynthetically active radiation (PAR) and canopy temperature (T~c~). These refinements are expected to enhance the reliability of carbon flux estimates and deepen our understanding of ecosystem carbon dynamics.

## Related Papers

### Methodology

#### Flux Data Post-Processing:

-   (Papale et al., 2006) the first paper came out on suggesting a standardized processing with EC data

Papale, D., Reichstein, M., Aubinet, M., Canfora, E., Bernhofer, C., Kutsch, W., Longdoz, B., Rambal, S., Valentini, R., Vesala, T., & Yakir, D. (2006). Towards a standardized processing of Net Ecosystem Exchange measured with eddy covariance technique: Algorithms and uncertainty estimation. *Biogeosciences*, *3*(4), 571–583. https://doi.org/10.5194/bg-3-571-2006

-   (Wutzler et al., 2018) introduces all important procedures that conduct by REddyProc for EC postprocessing steps.

Wutzler, T., Lucas-Moffat, A., Migliavacca, M., Knauer, J., Sickel, K., Šigut, L., Menzer, O., & Reichstein, M. (2018). Basic and extensible post-processing of eddy covariance flux data with REddyProc. Biogeosciences, 15(16), 5015–5030. https://doi.org/10.5194/bg-15-5015-2018

-   (Pastorello et al., 2020) the ONEFlux pipeline that currently formally employed by FLUXNET

Pastorello, G., Trotta, C., Canfora, E., Chu, H., Christianson, D., Cheah, Y.-W., Poindexter, C., Chen, J., Elbashandy, A., Humphrey, M., Isaac, P., Polidori, D., Reichstein, M., Ribeca, A., Van Ingen, C., Vuichard, N., Zhang, L., Amiro, B., Ammann, C., … Papale, D. (2020). The FLUXNET2015 dataset and the ONEFlux processing pipeline for eddy covariance data. *Scientific Data*, *7*(1), 225. https://doi.org/10.1038/s41597-020-0534-3

#### Daytime Partitioning:

-   (Lasslop et al., 2010) the theories under daytime partitioning

Lasslop, G., Reichstein, M., Papale, D., Richardson, A. D., Arneth, A., Barr, A., Stoy, P., & Wohlfahrt, G. (2010). Separation of net ecosystem exchange into assimilation and respiration using a light response curve approach: Critical issues and global evaluation. *Global Change Biology*, *16*(1), 187–208. https://doi.org/10.1111/j.1365-2486.2009.02041.x

-   (Lasslop et al., 2012) identify the proper driving temperature for partitioning

Lasslop, G., Migliavacca, M., Bohrer, G., Reichstein, M., Bahn, M., Ibrom, A., Jacobs, C., Kolari, P., Papale, D., Vesala, T., Wohlfahrt, G., & Cescatti, A. (2012). On the choice of the driving temperature for eddy-covariance carbon dioxide flux partitioning. Biogeosciences, 9(12), 5243–5259. https://doi.org/10.5194/bg-9-5243-2012
