---
title: "EC Partitioning"
---

## A story of Partitioning

The importance of eddy-covariace: 1) Having a global estimate based on observations and 2) These global gridded datasets are highly promising for land surface model validation and improvement (doi:10.1029/2010JG001593, 2011.)

The CO~2~ analyzer is measuring CO~2~ flux or what we called net ecosystem exchange (F~CO2~ or NEE), it's essentially a difference between ecosystem respiration (Reco) and gross primary production (GPP), as $NEE = Reco - GPP$. Partitioning is to partition the NEE measured by tower into GPP and Reco, which is important in flux data analysis [(Burba, 2022)](https://www.licor.com/env/products/eddy-covariance/ec-book/).

There are mainly two groups of NEE partitioning: one group methods are empirical models (establish site specifics relationship between nighttime flux and biophysical controls, then used the relationship to approximate daytime Reco). Another group of methods is more complex but less empirical models (light response curves using just daytime or 24-hour data) [(Burba, 2022)](https://www.licor.com/env/products/eddy-covariance/ec-book/).

<https://www.bgc-jena.mpg.de/5624848/Flux-partitioning>

Other Possible Ways on measuring Reco:

1\) Estimates from biogeochemical or soil–vegetation–atmosphere transfer (SVAT) models (<https://link.springer.com/article/10.1023/A:1002497616547>)

2\) From chamber measurements extrapolated to the stand scale (<https://doi.org/10.1046/j.1365-2486.1999.00214.x>; <https://pubmed.ncbi.nlm.nih.gov/11262922/>)

(Desai et al., 2007)

It is currently not possible to obtain direct, integrated observations of either GPP or RE, because these processes represent a multitude of responses by a combination of autotrophic and heterotrophic organisms.

Scaling from chamber level measurements to canopy level is labor intensive and fraught with high sampling uncertainty.

Nighttime Partitioning Drawbacks:

1\) frequent nighttime suppression of turbulence and dominance of advective fluxes not measured by conventional EC systems (Lasslop et al., 2010)

Accurately partitioning NEE into ER and GPP can:

1\) understanding the responses of the terrestrial carbon cycle to a changing climate, especially during extreme events (10.1088/1748-9326/9/3/035001)

2\) better understand the underlying mechanisms constraining ecosystem functions

3\) GPP and RECO estimates from EC are useful for modeling, supporting process-based model parameterization and validation, data assimilation, plant trait retrieval by model inversion, upscaling, as well as photosynthesis estimates based on remote sensing

With the coming up machine learning methods, how do you think compared with the algorithms (sulman et al., 2020; Weiwei et al., 2022)?

## Partitioning with REddyProc

(Wutzler et al., 2018) Read from 2024/10/31 to , check the paper here: https://doi.org/10.5194/bg-15-5015-2018

### Summary

## Estimation of global LAI and FAPAR using radiative transfer models (Myneni et al., 1997)

Read from 2024/10/30 to , check the paper here: 10.1109/36.649788

## On the temperature dependence of soil respiration (Lloyd & Taylor, 1994) - Nighttime Partitioning

From 2024/11/01 to , check the [paper](https://www.jstor.org/stable/2389824)

Research Qs:

-   Rx​ reflects the **baseline respiration rate** that is influenced by ecosystem factors like MMM.

-   f(T) captures the **temperature sensitivity** in a generalized form that applies across datasets.

1884 Van't Hoff derivative of the natural logarithm of the reaction rate constant (lnk) with respect to temperature (T). Van’t Hoff observed that the rate of chemical reactions changes exponentially with temperature. And the derivative of it in linear relationship. $$\frac{d(\ln k)}{dT} = \frac{E}{\mathcal{R}T^2} + c$$

1889 Arrhenius built on van’t Hoff’s observations and incorporated the concept of energy distribution among reacting molecules (based on Boltzmann's statistical mechanics). He simplified van’t Hoff’s equation by assuming c=0 and **integrating** it into a simpler form to explain reaction kinetics.

$$k = d e^{-\frac{E}{\mathcal{R}T}}$$

Where d is a constant, E is activation energy, T is the absolute temperature (K). But we would like to involve a reference temperature (283.15K), where standardize the temperature dependencies (enables consistent comparisons across data sets, standardizing variation between ecosystems).

$$R = R_{10} e^{\frac{E}{\mathcal{R} \cdot 283.15} \left(1 - \frac{283.15}{T}\right)}$$

Soil respiration involves changing populations of many different organisms, each undergoing a complex series of reactions, which is likely that the activation energies may indeed increase with decreasing temperature. Kavanau (1951) utilized kinetic theory to derive a semi-empirical formulation that effectively gives a decrease in activation energy with increasing temperature.

$$k_R = P \left[1 - e^{-\frac{E_0}{T - T_0}}\right]$$

A simplified version:

$$
R = A e^{-\frac{E_0}{T - T_0}}
$$

Final form relative to 10 celsius degree by Lloyd & Taylor, 1994:

$$R_{\text{eco}}(T) = R_{\text{eco,ref}} e^{E_0 \left( \frac{1}{T_{\text{Ref}} - T_0} - \frac{1}{T - T_0} \right)}$$

This equation indeed used to calculate Reco at night for nighttime partitioning method.

1898 Q10: [Van't Hoff in 1898](https://archive.org/details/lecturesontheore0000drjh/page/226/mode/2up) (p226-228) observed from the data he collected for T (temperature) vs k (reaction rate constant), for many chemical reactions, the k typically increases by a factor of 2 to 3 for every 10°C increase in temperature \[T VS. Reaction Rates\]. This is in exponential relationship. To further test if reaction rates are in certain times for 10°C intervals, we used: $log_{10}k = a +bt$ & $(k_{t+10})/k_t = 10^{10b}$

This make us available to calculate any ratios, such as for ethyl acetate: 9.4°C k=2.307 & 44.94°C k=21.648, sub to $log_{10}k = a +bt$, we are able to calculate b and then $10^{10b}$ to get the ratios.

The idea posted by Van't Hoff was further widely used in ecology study.

## On the seperation of net ecosystem exchange into assimilation and ecosystem respiration: review and improved algorithm (Reichstein, 2005)

From 2024/11/24 to , check the paper [here](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1365-2486.2005.001002.x): doi: 10.1111/j.1365-2486.2005.001002.x

Main Research Question: analyse the effect of short-term vs. long-term temperature sensitivity on the estimation of daytime Reco and GPP.

-   (The observed seasonal temperature sensitivity of ecosystem respiration includes influences from other factors (e.o., soil moisture, growth) that vary with temperature, making it different from the actual short-term temperature sensitivity.)

Improved Algorithm:

-   Collect half-hourly eddy covariance flux data, ensuring high-quality night-time data through a turbulence filtering threshold.

-   Segment the data into 15-day windows, with a 10-day overlap between consecutive windows.

-   Perform short-term regressions within each window to estimate temperature sensitivity (E0).

-   Linearly interpolate Rref based on estimates from 4-day periods and integrate E0, short into respiration calculations.

-   Use the improved algorithm to partition NEE into GEP and Reco while addressing biases from long-term temperature sensitivity.

$$R_{\text{eco}}(T) = R_{\text{eco,ref}} e^{E_0 \left( \frac{1}{T_{\text{Ref}} - T_0} - \frac{1}{T - T_0} \right)}$$

T~0~ is kept constant at -46.02 celsius degrees; T~ref~ is set to 10 celsius degrees in (Reichstein, 2005) and 15 celsius degrees in (Lasslop et al., 2010). E~0~, temperature sensitivity is a constant value used for the whole year in (Lasslop et al., 2010) and in a short periods in (Reichstein, 2005), R~eco,ref~ was estimated every 5 days using a 15 days window.

Log formed:

$$\ln(R_{\text{eco}}(T)) = \ln(R_{\text{eco,ref}}) + E_0 \left( \frac{1}{T_{\text{ref}} - T_0} - \frac{1}{T - T_0} \right)$$

Thus, ln (Reco,ref) as the intercept, E0 temperature sensitivity as slope.

Using daytime temperature, respiration is extrapolated to the daytime and the difference between modeled R~eco~ and measured NEE yields estimated GPP. We refer to this estimate as ‘NB’ (nighttime data-based).

The paper for REddyProc package: <https://bg.copernicus.org/articles/15/5015/2018/>

## Daytime flux partitioning method -\> Lasslop et al. (2010)

**Daytime flux partitioning method -\> Lasslop et al. (2010)**

Light–response curves are fit to daytime NEE measurements and respiration is estimated from the intercept of the ordinate, which avoids the use of potentially problematic nighttime data.

Falge et al. (2001)

Biases of nighttime partitioning methods:

Lasslop et al. (2010)

Methods that rely on nighttime data for partitioning may be biased due to the frequent nighttime suppression of turbulence and dominance of advective fluxes not measured by conventional EC systems (Goulden et al., 1996; Aubinet et al., 2000; Feigenwinter et al., 2004; Aubinet, 2008).

Daytime data-based estimate including temperature sensitivity of respiration.

[(Michaelis and Menten, 1913](https://www.chem.uwec.edu/Chem352_F18/pages/readings/media/Michaelis_&_Menton_1913.pdf)) examines the concentration of sucrose affects the rate of its enzymatic inversion, models how reaction velocity (rate of product formation) depends on the substrate concentration. Which expresses reaction rate as a hyperbolic function:

$$v = \frac{V_{\text{max}}[S]}{K_m + [S]}$$

where $V_{max}$​ is the maximum rate, \[S\] is the substrate concentration, and $K_m$​ is the Michaelis constant (substrate concentration at half-maximum rate).

Rectangular hyperbolic light-response curve (Falge et al., 2001)

$$\begin{equation}\mathrm{NEE} = \frac{\alpha \beta R_g}{\alpha R_g + \beta} + \gamma\end{equation}$$

$\alpha \, (\mu\text{mol C J}^{-1})$ is the canopy light utilization efficiency and represents the initial slope of the light–response curve

$\beta \, (\mu\text{mol C m}^{-2} \text{s}^{-1})$ is the maximum CO2 uptake rate of the canopy at light saturation

$\gamma \, (\mu\text{mol C m}^{-2} \text{s}^{-1})$ is the ecosystem respiration

$R_g \, ({W m}^{-2})$ is the global radiation

Gilmanov et al. (2003) consider the temperature sensitivity of the Reco, thus combined with Llyod & Taylor (1994), then:

$$\begin{equation}\mathrm{NEE} = \frac{\alpha \beta R_g}{\alpha R_g + \beta} + R_{\text{eco,ref}} e^{E_0 \left( \frac{1}{T_{\text{Ref}} - T_0} - \frac{1}{T - T_0} \right)}\end{equation}$$

There are two ways in estimating parameters:

a\) E~0~ was estimated using nighttime data, R~eco,ref~, alpha, beta were derived from daytime data ; b) All parameters were estimated using daytime data.

With the consideration of VPD limitation, β could be further interpreted as with an exponential decreasing function (Korner, 1995)

$$
\beta =\begin{cases} \beta_0 \exp(-k(\text{VPD} - \text{VPD}_0)), & \text{VPD} > \text{VPD}_0, \\\beta_0, & \text{VPD} \leq \text{VPD}_0.\end{cases}
$$

## Partitioning net carbon dioxide fluxes into photosynthesis and respiration using neural networks -\> (Tramontana et al., 2020)

## **Widespread inhibition of daytime ecosystem respiration (Keenan et al., 2019)**

<https://www.nature.com/articles/s41559-019-0809-2#ref-CR12> With the consideration of the inhibition of leaf respiration in the light

The daytime and nighttime approaches are built on the assumption that the reference respiration rate (*R*~ref~) does not change between night and day. If there's inhibition of leaf respiration in the light, then nighttime method will overestimate daytime respiration and the daytime method will underestimate the nighttime respiration

Here, modified both the standard daytime and night-time partitioning methods to account for an apparent inhibition by estimating and applying Rref nighttime and Rref daytime separately.

## 2025/04/08 Partitioning through GPP-SIF (Weiwei et al., 2022)\*\* Revisit need

Problem with current methods: Both NT and DT methods rely on simplified empirical methods, which have structural errors. Simplified ER parameterization: 1) E0 and Rref remain same through day and night 2) Reco only rely on air or soil T Fail to capture fast environmental change

What the research did? In this study, we show that a new NN framework informed by SIF observations (NNSIF) can tackle two problems simultaneously: (1) partitioning NEE into GPP and ER without prescribed empirical models, and (2) unraveling the GPP-SIF relationship at the ecosystem scale.

Key concept here: Solar-induced chlorophyll fluorescence (SIF) is the faint light re-emitted by chlorophyll during photosynthesis under natural sunlight, serving as a passive, remote indicator of plant photosynthetic activity.

During photosynthesis, chlorophyll molecules absorb light energy. This energy can follow three main pathways:1) Drive photochemistry (photosynthesis) – powering electron transport, 2) Be dissipated as heat and 3) Be re-emitted as fluorescence (a small portion, \<5%). Thus, GPP can be related to SIF as SIF is a byproduct of the light reactions of photosynthesis, meaning it originates from the same absorbed light energy that drives carbon fixation — so higher photosynthetic activity generally results in stronger SIF signals.

## 2025/04/09 On the choice of driving temperature for eddy-covariance carbon dioxide flux partitioning (Lasslop et al., 2012)

Main objective: investigate the potential of air and soil temperatures, also surface temperatures, as drivers for night-time partitioning algorithms; quantify the uncertainty and potential biases arising from the choice of the driving temperature for respiration.

Conclusion: The highest performance was achieved with an averaged temperature with optimised weights, in spite of the cost of having an additional parameter. We recommend site specific evaluations to determine which temperature explains most of the variability of the ecosystem respiration (nighttime NEE). As surface temperature showed a good correlation with nighttime NEE, observations of longwave radiation or surface temperature could be a useful extension of the measurements at flux sites.

Important Points: Keeping the model’s structure simple is an important goal in order to remain as close as possible to the data, to avoid additional assumptions, and to avoid additional sources of uncertainty.

For a subset of sites, observations of the longwave radiation were available and Tsurf could be considered. For this subset of sites, the mean correlation coefficients computed between NEE and different temperature streams were not significantly different. We again observed the Topt had the greatest correlation with nighttime NEE (median = 0.367). For Tmean the median correlation was 0.346, followed by Tsurf derived from longwave radiation (0.339) (no figure). Tsoil, for this subset, showed a stronger correlation (0.332) than the air temperature (0.325).

Methods on examining correlations:

1.  Sliding Window Correlation: 12-day moving window. For each 12-day window, calculated the correlation between nighttime NEE and different temperature variables, half-hourly. Using median correlations
2.  Built linear models and use AIC to check which temperature explains the most variability of NEE\
    AIC = n log (RSS/n) + 2 (p+1)

## 2025/04/10 Revisiting the choice of the driving temperature for eddy covariance CO2 flux partitioning (Wohlfahart & Galvagno, 2016)

Main objective: revisit the effects related to the choice of the driving temperature on inferred GPP and Reco

Methods:

Using grassland and temperatures for surface temperaturem, soil temperature at 0.02m and 0.1m

1\) Seperate daytime, nighttime Reco for the same temeprature, to compare

If different -\> there is sth other than light inhibition problem, is that interchangeable for Reco, day and Reco, night, both used a temperature?

2\) Fit in the logtransformed Reco and T to llyod equation, check slopes (how sensitive Reco is to T change) and y-intercepts (Reco at reference T) between day and night Reco -\> Check if Reco responds to temperature in the same way during both day and night

Opaque chambers for daytime and nighttime measurements -\> mimic the daytime, nighttime Reco extrapolated from the Llyod equations

Key findings:

-   The diurnal course of Reco, in contrast, reflects the additive contributions of both below- and aboveground respiration (Eq. (1)) and reaches minima/maxima after that of air and before that of soil temperature (Fig. 1a).

Ts (explains Rbg; more likely influence the Reco at night)\
Ta (explains Rag; more likely influence Reco at day)

If using Ts to estimate the Reco for day -\> daytime Ta responds faster -\> underestimate the Reco at day\
If using Ta to estimate the Reco for day -\> Ta changes fast but Reco not that fast since a big portion from Rbg, thus steeper E0, overestimate the Reco.\
Thus, nighttime Reco is overestimated based on soil temperature and underestimated based on air temperature

The magnitude of the over or underestimation depends on 1) phase shift between Ts and Ta (**time lag** between their daily **maxima** (or minima) during a typical diurnal cycle) and 2) the magnitude of soil and above-ground respiration

## Problems with Partitioning Algorithms in Deriving GPP and Reco

1.  Light Inhibition Problems (daytime lower Reco)
2.  hysteresis can lead to systematic under- or overestimation in flux-partitioning algorithms that selectively fit only daytime or nighttime data and then extrapolate the model in time.

## 2025/04/20 History of EC Partitioning

Webb, E.K., Pearman, G.I., Leuning, R., 1980. Correction of flux measurements for density effects due to heat and water vapor transfer. Q. J. R. Meteorol. Soc. 106, 85–100.

**1972** - [(Desjardins, 1972)](https://www.proquest.com/openview/509c986b0ec387de6f4618203c677d59/1?cbl=18750&diss=y&pq-origsite=gscholar) [(Desjardins, 1974)](https://link.springer.com/article/10.1007/BF00123493) Desjardins developed the first eddy covariance flux tower to measure CO₂ during his PhD research, titled "A study of CO₂ and sensible heat fluxes using the eddy correlation technique."

(Morgenstern et al., 2004) The authors chose the Q₁₀ model over the activation energy (Arrhenius) model because both gave similar fits, but the Q₁₀ model allowed for a statistically more appropriate linear regression via logarithmic transformation, helping to deal with noise and heteroscedasticity in EC data.

$$
\begin{equation}R = A e^{BT} = R_{\text{ref}} Q_{10}^{(T - T_{\text{ref}})/10}\end{equation}
$$

（Gilmanov et al., 2003) The first empirically based estimates of GPP
