---
title: ""
---

## QE Preparations Timeline

+---------------+---------------------------------------------+-----------------------------------------------------------+
| Dates         | Duty                                        | Notes                                                     |
+===============+=============================================+===========================================================+
| 08/07-08/23   | Chapter 1 Literature Glance                 | 15 Days                                                   |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 08/25         | Chapter 1 Proposal & Bibliography Writing   |                                                           |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 08/26-09/17   | Chapter 2 Literature Glance                 | 20 Days                                                   |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 09/18-09/20   | Chapter 1&2 Proposal & Bibliography Writing | 3 Days                                                    |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 09/22-10/11   | Chapter 3 Literature Glance                 | 18 Days                                                   |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 10/13-10/14   | Bibliography Writing                        | 2 Days                                                    |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 10/15-10/17   | Proposal Writing                            | 3 Days \[5000-10000 words, 12 font size, double spacing\] |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 10/18         | Revision of Bibliography                    |                                                           |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 10/27-11/22   | Review 24 submitted papers                  | 24 Days                                                   |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| Week of 11/24 | PhD CE                                      |                                                           |
+---------------+---------------------------------------------+-----------------------------------------------------------+
| 12/12         | PhD OE                                      |                                                           |
+---------------+---------------------------------------------+-----------------------------------------------------------+

## QE Deadlines

+------------------+---------------------------------------------+---------------------------------+
| Dates            | Submissions                                 | Notes                           |
+==================+=============================================+=================================+
| 09/22            | Chapter 1&2 Proposal and Bibliography DRAFT | Submit to Remi                  |
+------------------+---------------------------------------------+---------------------------------+
| 10/14            | Bibliography DRAFT                          | Submit to Remi                  |
+------------------+---------------------------------------------+---------------------------------+
| 10/20 the best\  | Bibliography FINAL                          | Submit to all committee members |
| 10/27 the latest |                                             |                                 |
|                  |                                             | Suggest 2 months                |
+------------------+---------------------------------------------+---------------------------------+
| 10/20            | Proposal DRAFT                              | Submit to Remi                  |
+------------------+---------------------------------------------+---------------------------------+
| 11/07 the latest | Proposal FINAL                              | Submit to all committee members |
|                  |                                             |                                 |
|                  |                                             | Suggest 6-8 weeks               |
+------------------+---------------------------------------------+---------------------------------+
| 11/28            | Submission of CE                            | Submit to all committee members |
+------------------+---------------------------------------------+---------------------------------+
| 12/12            | Oral Presentation                           |                                 |
+------------------+---------------------------------------------+---------------------------------+
